<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.9.0-beta.1</Version>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GangBeasts.GameLibs" Version="1.27.0" />
    <PackageReference Include="LavaGang.MelonLoader" Version="0.7.3" />
  </ItemGroup>
  <ItemGroup><Compile Remove="tests/**/*.cs" /><Compile Remove="dist/**/*.cs" /></ItemGroup>
</Project>
